# Generated by Django 4.2.2 on 2023-07-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
