# Generated by Django 4.2.3 on 2023-07-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Labels',
            new_name='labels',
        ),
    ]
